# Generated by Django 3.1.1 on 2020-09-12 10:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroomId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Last Name', max_length=100)),
                ('studentId', models.CharField(help_text='First Name', max_length=8)),
                ('attendanceClassroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.classroom')),
            ],
            options={
                'ordering': ['studentId'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=100)),
                ('last_name', models.CharField(help_text='Last Name', max_length=100)),
                ('teacherId', models.CharField(help_text='First Name', max_length=8)),
            ],
            options={
                'ordering': ['teacherId'],
            },
        ),
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.classroom')),
                ('studentList', models.ManyToManyField(help_text='Select students for this classrrom', to='catalog.Student')),
            ],
            options={
                'ordering': ['classroom'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='currentTeacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.teacher'),
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the beacon', primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=20)),
                ('minor', models.CharField(max_length=20)),
                ('remarks', models.TextField(help_text='Enter remarks of the beacon', max_length=1000)),
                ('classroomId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.classroom')),
            ],
            options={
                'ordering': ['classroomId'],
            },
        ),
    ]
