# Generated by Django 3.1.1 on 2020-09-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200914_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display Name in App', max_length=127),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='EE', help_text='Deparment', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(default='CDE', help_text='Deparment', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='EE', help_text='Deparment', max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='display_name',
            field=models.CharField(default='EE', help_text='Display Name in App', max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='currentTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendanceClassroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.classroom'),
        ),
    ]
