# Generated by Django 3.1.1 on 2020-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit_code',
            field=models.CharField(default='EE', max_length=20),
            preserve_default=False,
        ),
    ]
