# Generated by Django 3.1.1 on 2020-09-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200921_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='venue',
        ),
        migrations.AddField(
            model_name='class',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.classroom'),
        ),
    ]
