# Generated by Django 3.1.1 on 2020-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200921_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
