# Generated by Django 3.1.2 on 2020-10-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_student_taking_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(editable=False, max_length=15)),
                ('record', models.CharField(editable=False, max_length=511)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
